name: Docker Release

on:
  release:
    types: [released, edited]
  
jobs:                                                       # 1 to many jobs per workflow
    build-and-push:                                           # ID of this job
      name: Build and Push Docker Image to Github Packages    # Name of job to be printed on Github UI
      runs-on: ubuntu-latest                                  # Runner for the job
      steps:                                                  # Steps for the job
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
  
